[project]
name = "ai-career-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Umair Ahmed Siddiqui", email = "prof.umair.siddiqui@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "openai-agents>=0.22.0",
    "pypdf>=6.16.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "streamlit>=1.62.0",
]

[project.scripts]
ai-career-copilot = "ai_career_copilot:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
